image: node:8.9

cache:
  paths:
    - node_modules/

before_script:
  - npm install gitbook-cli@2.3.2 -g
  - gitbook fetch 3.2.3
  - gitbook install

pages:
  stage: deploy
  only:
    - master
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
